import{S as E,a as M,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const p=document.querySelector(".form"),d=document.querySelector(".js-gallery"),n=document.querySelector(".js-load-more");function u(){d&&(d.innerHTML="")}const b=document.querySelector(".loader"),P=()=>b&&b.classList.add("is-active"),h=new E(".gallery a",{captionsData:"alt",captionDelay:250});function L(a){if(!Array.isArray(a)||!d){u();return}const t=a.map(o=>{const{largeImageURL:s="#",webformatURL:e="",tags:r="",likes:c=0,views:v=0,comments:A=0,downloads:q=0}=o||{};return`
      <li class="gallery-item">
        <a class="gallery-link js-gallery-link" href="${s}">
          <img class="gallery-image" src="${e}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${c}</p>
          <p class="info-item"><span>Views:</span> ${v}</p>
          <p class="info-item"><span>Comments:</span> ${A}</p>
          <p class="info-item"><span>Downloads:</span> ${q}</p>
        </div>
      </li>`}).join("");d.insertAdjacentHTML("beforeend",t),h&&typeof h.refresh=="function"&&h.refresh()}function w(){n&&n.classList.remove("is-hidden")}function m(){n&&n.classList.add("is-hidden")}const B="53360478-1bf245edf032d22b013a2c514",N="https://pixabay.com/api/";async function S(a,t=1){if(!a)return null;const o=Math.max(1,Number(t)||1),s={key:B,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};P();try{const{data:e}=await M.get(N,{params:s});return e}catch(e){throw e}}p?p.addEventListener("submit",$):console.warn("Search form not found (.form)");n&&n.addEventListener("click",x);let g="",y=1,f=0,l=0;async function $(a){a.preventDefault();const o=a.currentTarget.elements["search-text"],s=(o&&o.value||"").trim();if(!s){i.warning({message:"The input must not be empty"});return}g=s,y=1,f=0,l=0,u(),m();try{const e=await S(s,y);if(!e||!Array.isArray(e.hits)||e.hits.length===0){u(),i.info({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"center"});return}L(e.hits),f=Number(e.totalHits)||0,l+=e.hits.length,l<f?w():m()}catch{u(),i.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"bottomCenter"})}}async function x(a){if(g){n&&(n.disabled=!0),y+=1;try{const t=await S(g,y);if(!t||!Array.isArray(t.hits)||t.hits.length===0){m(),i.info({message:"We're sorry, but there are no more images to load.",position:"bottomCenter"});return}L(t.hits),l+=t.hits.length;try{const o=document.querySelector(".gallery .gallery-item");if(o){const{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{}l>=(Number(f)||0)?(m(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch(t){console.error(t),i.error({message:"Error loading more images — please try again."})}finally{n&&(n.disabled=!1)}}}
//# sourceMappingURL=index.js.map
