import{a as P,S as N,i}from"./assets/vendor-DvfmeZXB.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const $="53360478-1bf245edf032d22b013a2c514",x="https://pixabay.com/api/",b=async(a,r=1)=>{if(!a)return null;const o=Math.max(1,Number(r)||1),s={key:$,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};try{return(await P.get(x,{params:s})).data}catch(e){throw e}},L=document.querySelector(".form"),d=document.querySelector(".js-gallery"),n=document.querySelector(".js-load-more");function u(){d&&(d.innerHTML="")}const m=document.querySelector(".loader");function w(){m&&m.classList.add("is-active")}function v(){m&&m.classList.remove("is-active")}const p=new N(".gallery a",{captionsData:"alt",captionDelay:250});function S(a){if(!Array.isArray(a)||!d){u();return}const r=a.map(o=>{const{largeImageURL:s="#",webformatURL:e="",tags:t="",likes:c=0,views:q=0,comments:E=0,downloads:M=0}=o||{};return`
      <li class="gallery-item">
        <a class="gallery-link js-gallery-link" href="${s}">
          <img class="gallery-image" src="${e}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${c}</p>
          <p class="info-item"><span>Views:</span> ${q}</p>
          <p class="info-item"><span>Comments:</span> ${E}</p>
          <p class="info-item"><span>Downloads:</span> ${M}</p>
        </div>
      </li>`}).join("");d.insertAdjacentHTML("beforeend",r),p&&typeof p.refresh=="function"&&p.refresh()}function A(){n&&n.classList.remove("is-hidden")}function h(){n&&n.classList.add("is-hidden")}let g="",y=1,f=0,l=0;async function B(a){a.preventDefault();const o=a.currentTarget.elements["search-text"],s=(o&&o.value||"").trim();if(!s){i.warning({message:"The input must not be empty"});return}g=s,y=1,f=0,l=0,u(),h(),w();try{const e=await b(s,y);if(!e||!Array.isArray(e.hits)||e.hits.length===0){u(),i.info({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"center"});return}S(e.hits),f=Number(e.totalHits)||0,l+=e.hits.length,l<f?A():h()}catch{u(),i.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"bottomCenter"})}finally{v()}}async function C(a){if(g){n&&(n.disabled=!0),y+=1,w();try{const r=await b(g,y);if(!r||!Array.isArray(r.hits)||r.hits.length===0){h(),i.info({message:"We're sorry, but there are no more images to load.",position:"bottomCenter"});return}S(r.hits),l+=r.hits.length;try{const o=document.querySelector(".gallery .gallery-item");if(o){const{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{}l>=(Number(f)||0)?(h(),i.info({message:"We're sorry, but you've reached the end of search results."})):A()}catch(r){console.error(r),i.error({message:"Error loading more images — please try again."})}finally{n&&(n.disabled=!1),v()}}}L?L.addEventListener("submit",B):console.warn("Search form not found (.form)");n&&n.addEventListener("click",C);
//# sourceMappingURL=index.js.map
