import{S as E,a as M,i}from"./assets/vendor-DvfmeZXB.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const L=document.querySelector(".form"),d=document.querySelector(".js-gallery"),n=document.querySelector(".js-load-more");function u(){d&&(d.innerHTML="")}const m=document.querySelector(".loader"),P=()=>m&&m.classList.add("is-active"),B=()=>m&&m.classList.remove("is-active"),g=new E(".gallery a",{captionsData:"alt",captionDelay:250});function b(a){if(!Array.isArray(a)||!d){u();return}const t=a.map(o=>{const{largeImageURL:s="#",webformatURL:e="",tags:r="",likes:c=0,views:S=0,comments:A=0,downloads:q=0}=o||{};return`
      <li class="gallery-item">
        <a class="gallery-link js-gallery-link" href="${s}">
          <img class="gallery-image" src="${e}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><span>Likes:</span> ${c}</p>
          <p class="info-item"><span>Views:</span> ${S}</p>
          <p class="info-item"><span>Comments:</span> ${A}</p>
          <p class="info-item"><span>Downloads:</span> ${q}</p>
        </div>
      </li>`}).join("");d.insertAdjacentHTML("beforeend",t),g&&typeof g.refresh=="function"&&g.refresh()}function w(){n&&n.classList.remove("is-hidden")}function y(){n&&n.classList.add("is-hidden")}const N="53360478-1bf245edf032d22b013a2c514",$="https://pixabay.com/api/";async function v(a,t=1){if(!a)return null;const o=Math.max(1,Number(t)||1),s={key:N,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};P();try{const{data:e}=await M.get($,{params:s});return e}finally{B()}}L?L.addEventListener("submit",x):console.warn("Search form not found (.form)");n&&n.addEventListener("click",C);let p="",h=1,f=0,l=0;async function x(a){a.preventDefault();const o=a.currentTarget.elements["search-text"],s=(o&&o.value||"").trim();if(!s){i.warning({message:"The input must not be empty"});return}p=s,h=1,f=0,l=0,u(),y();try{const e=await v(s,h);if(!e||!Array.isArray(e.hits)||e.hits.length===0){u(),i.info({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"center"});return}b(e.hits),f=Number(e.totalHits)||0,l+=e.hits.length,l<f?w():y()}catch{u(),i.error({message:"Sorry, there are no images matching your search query. Please try again!",color:"red",position:"bottomCenter"})}}async function C(a){if(p){n&&(n.disabled=!0),h+=1;try{const t=await v(p,h);if(!t||!Array.isArray(t.hits)||t.hits.length===0){y(),i.info({message:"We're sorry, but there are no more images to load.",position:"bottomCenter"});return}b(t.hits),l+=t.hits.length;try{const o=document.querySelector(".gallery .gallery-item");if(o){const{height:s}=o.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"})}}catch{}l>=(Number(f)||0)?(y(),i.info({message:"We're sorry, but you've reached the end of search results."})):w()}catch(t){console.error(t),i.error({message:"Error loading more images — please try again."})}finally{n&&(n.disabled=!1)}}}
//# sourceMappingURL=index.js.map
